# Generated by Django 2.2.10 on 2020-07-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa fa-facebook'), ('instagram', 'fa fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('linkedin', 'fa-linkedin-in'), ('twitter', 'fa fa-twitter')], max_length=20),
        ),
    ]
