# Generated by Django 2.2.10 on 2020-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200711_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/Presentation'),
        ),
    ]
